name: GET
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 1.11
  - torchvision
  - cudatoolkit >= 11.3.1
  - pip:
    - torchdeq
    - timm
    - diffusers
    - pytorch-gan-metrics
    - piq
